// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Member struct {
	ID    uint32
	Name  string
	Image string
}

type Mod struct {
	ID          uint32
	Name        string
	Description string
	Image       sql.NullString
}
