// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createMember = `-- name: CreateMember :execresult
INSERT INTO members (
    ` + "`" + `name` + "`" + `,
    ` + "`" + `image` + "`" + `
) VALUES (
    ?, ?
)
`

type CreateMemberParams struct {
	Name  string
	Image string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMember, arg.Name, arg.Image)
}

const createMod = `-- name: CreateMod :execresult
INSERT INTO mods (
    ` + "`" + `name` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `image` + "`" + `
) VALUES (
    ?, ?, ? 
)
`

type CreateModParams struct {
	Name        string
	Description string
	Image       sql.NullString
}

func (q *Queries) CreateMod(ctx context.Context, arg CreateModParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMod, arg.Name, arg.Description, arg.Image)
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = ?
`

func (q *Queries) DeleteMember(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteMember, id)
	return err
}

const deleteMod = `-- name: DeleteMod :exec
DELETE FROM mods WHERE id = ?
`

func (q *Queries) DeleteMod(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteMod, id)
	return err
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, image FROM members
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.Name, &i.Image); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMods = `-- name: ListMods :many
SELECT id, name, description, image FROM mods
`

func (q *Queries) ListMods(ctx context.Context) ([]Mod, error) {
	rows, err := q.db.QueryContext(ctx, listMods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mod
	for rows.Next() {
		var i Mod
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
