services:
  app:
    container_name: lesfraternels_website_app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    ports:
     - 9000:9000
    volumes:
      - ./:/var/www/html
  
  nginx:
    container_name: lesfraternels_website_nginx
    image: nginx:stable-alpine3.21
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app