// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Creator struct {
	ID   uint32
	Name string
}

type Member struct {
	ID    uint32
	Name  string
	Image string
}

type Mod struct {
	ID          uint32
	Name        string
	Description string
	Image       sql.NullString
}

type ModsCreator struct {
	ID        uint32
	ModID     uint32
	CreatorID uint32
}

type ModsTag struct {
	ID    uint32
	ModID uint32
	TagID uint32
}

type Tag struct {
	ID   uint32
	Name string
}
